#define ARMSSELECT_Y	24
#define ITEMSELECT_Y	(ARMSSELECT_Y+52)


#define MYLIFE_X	16
#define MYLIFE_Y	(16+24)//(SURFACE_HEIGHT-24)
#define ARMSENERGY_X	16
#define ARMSENERGY_Y	16//(SURFACE_HEIGHT-48)

